This is a notebook for training using Random Forest Regressor.

In [10]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [5]:
train_df = pd.read_csv("./inputs/train.csv").set_index("id")
target = train_df["Listening_Time_minutes"]
train_df.drop("Listening_Time_minutes", axis=1, inplace=True)
train_df

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
id,,,,,,,,,,
0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive
1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative
2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative
3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive
4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral
...,...,...,...,...,...,...,...,...,...,...
749995,Learning Lab,Episode 25,75.66,Education,69.36,Saturday,Morning,NaN,0.0,Negative
749996,Business Briefs,Episode 21,75.75,Business,35.21,Saturday,Night,NaN,2.0,Neutral
749997,Lifestyle Lounge,Episode 51,30.98,Lifestyle,78.58,Thursday,Morning,84.89,0.0,Negative
749998,Style Guide,Episode 47,108.98,Lifestyle,45.39,Thursday,Morning,93.27,0.0,Negative
749999,Sports Central,Episode 99,24.10,Sports,22.45,Saturday,Night,36.72,0.0,Neutral

In [6]:
# Encode the categorical columns
%store -r categories
# categories = categories[:1] + categories[2:]
display(categories)
encoder = LabelEncoder()
for column in categories:
    train_df[column] = encoder.fit_transform(train_df[column])

train_df[categories]

['Podcast_Name',
 'Episode_Title',
 'Genre',
 'Publication_Day',
 'Publication_Time',
 'Episode_Sentiment']

,Podcast_Name,Episode_Title,Genre,Publication_Day,Publication_Time,Episode_Sentiment
id,,,,,,
0,34,98,9,4,3,2
1,24,19,1,2,0,0
2,40,8,2,5,1,0
3,10,40,8,1,2,2
4,31,85,3,1,0,1
...,...,...,...,...,...,...
749995,26,18,2,2,2,0
749996,2,14,0,2,3,1
749997,28,47,4,4,2,0
749998,41,42,4,4,2,0
749999,38,99,7,2,3,1

In [8]:
# Scale the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(train_df)
scaled_data

array([[ 0.74158935,  1.69278629,         nan, ...,         nan,
        -1.1717663 ,  1.22882316],
       [ 0.03425408, -1.10995773,  1.6771601 , ...,  0.83348105,
         0.56565749, -1.22384261],
       [ 1.16599051, -1.50021322,  0.2849676 , ..., -1.52072397,
        -1.1717663 , -1.22384261],
       ...,
       [ 0.31718819, -0.1165801 , -1.01683855, ...,  1.14770311,
        -1.1717663 , -1.22384261],
       [ 1.23672404, -0.29396896,  1.34897877, ...,  1.44224234,
        -1.1717663 , -1.22384261],
       [ 1.02452346,  1.72826406, -1.22551577, ..., -0.54537029,
        -1.1717663 ,  0.00249027]])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, target, test_size=0.2, random_state=42)

In [12]:
model = RandomForestRegressor()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
score = root_mean_squared_error(y_test, predictions)
print(score)

12.672146955473128